export enum RoutesPath {
    LOGIN = "/login",
    FORGOT_PASSWORD = "/forgot-password",
    INDEX = "/",
    SCHEDULE = "/schedule",
    CREATE_SCHEDULE = "/create-schedule",
    DEPARTMENTS = "/departments",
    EMPLOYEE_WITH_PARAM = "/:id/employees",
    ABOUT = "/about",
    ADD_EMPLOYEE = "/add-employee",
    EDIT_EMPLOYEE = "/edit-employee/",
    EDIT_EMPLOYEE_WITH_PARAM = "/edit-employee/:id",
    AVAILABILITIES = "/availabilities",
    RESET_PASSWORD = "/reset-password",
    CHANGE_PASSWORD = "/change-password",
    MANAGE_AVAILABILITIES = "/manage-availabilities",
    ON_LOGIN_SUCCESS_ROUTE = "/",
}
